# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: /bin/zsh

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: auto

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: auto

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 90

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: solid
  title: null
  # style: []
  # title: Terminalizer
  style:
    border: 0px black solid
    boxShadow: none
    margin: 0px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "Hack Nerd Font Regular, Ubuntu Mono, Monospace"

# The size of the font
fontSize: 22

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "#1c1c1c"
  foreground: "#707880"
  cursor: "#707880"
  black: "#1c1c1c"
  red: "#D78700"
  green: "#5F8700"
  yellow: "#AFAF5F"
  blue: "#87AFD7"
  magenta: "#875F87"
  cyan: "#D75F5F"
  white: "#A3ABB3"
  brightBlack: "#1c1c1c"
  brightRed: "#D78700"
  brightGreen: "#5F8700"
  brightYellow: "#AFAF5F"
  brightBlue: "#87AFD7"
  brightMagenta: "#875F87"
  brightCyan: "#D75F5F"
  brightWhite: "#A3ABB3"
